version: "3.8"

services:
  open_liberty_admin_center:
    container_name: my_open_liberty_admin_center
    build: .
    ports:
      - "9081:9081"
      - "9443:9443"
    networks:
      - docker_pirate_net
    deploy:
      resources:
        limits:
          memory: 2G

networks:
  docker_pirate_net:
    driver: bridge
    name: docker_pirate_net
