version: "3.8"

services:
  ibm_mq_santi:
    container_name: my_ibm_mq_santi
    build: ./mq/
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=SANTI_QMGR # Queue Manager name
      - MQ_ADMIN_PASSWORD=santi_admin_password # Password of the "admin" user
      - MQ_APP_PASSWORD=santi_app_password # Password for the "app" user (DEV.APP.SVRCONN channel becomes)
      - MQ_ENABLE_METRICS=true # To enable Prometheus metrics (port 9157)
      - MQ_DEV=false # Set this to false to stop default DEV objects being created (hardcore mode)
      - MQ_ENABLE_EMBEDDED_WEB_SERVER=true # Set this to false if you do not need the web console
    ports:
      - "1414:1414"
      - "9443:9443"
      - "9157:9157" # Prometheus port (only when metrics are enabled)
    # volumes:
    # - docker_pirate_ibm_mq_vol:/mnt/mqm
    networks:
      - docker_pirate_net
    deploy:
      resources:
        limits:
          memory: 2G
  app_santi:
    container_name: my_app_santi
    build: ./app/
    environment:
      # Environment variables to authenticate to Java app for connecting to MQ
      - APP_USER=app
      - APP_PASSWORD=santi_app_password
    depends_on:
      - ibm_mq_santi
    networks:
      - docker_pirate_net
    deploy:
      resources:
        limits:
          memory: 2G

# volumes:
#   docker_pirate_ibm_mq_vol:
#     name: docker_pirate_ibm_mq_vol

networks:
  docker_pirate_net:
    driver: bridge
    name: docker_pirate_net
